node {

   container = "hello"

   env.DOCKER_API_VERSION="1.23"

   stage 'checkout'
   git url: "http://gogs:3000/gogs/${container}.git"


   stage 'get hash'

   sh "git rev-parse --short HEAD > commit-id"                        
   commit_id = readFile('commit-id').replace("\n", "").replace("\r", "")


   stage 'build'

   sh "docker build -t localhost:5000/${container}:${commit_id} ."

   stage 'test'

   sh "docker run --rm localhost:5000/${container}:${commit_id} npm test"

   stage 'push'

   sh "docker push localhost:5000/${container}:${commit_id}"

   stage 'deploy'
   
   sh "kubectl set image --local -o yaml -f deploy.yml hello=localhost:5000/${container}:${commit_id} > deploynew.yml"
   sh "kubectl apply -f deploynew.yml"
   
}